# Generated by Django 5.1 on 2025-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom / Prénom')),
                ('phone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('budget', models.CharField(blank=True, max_length=50, null=True, verbose_name='Budget estimé')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
        ),
    ]
